### ISSUE TITLE
Inconsistent structure of message bubbles

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#658]
Real message bubbles and quoted message bubbles (the ones you see when replying to a message) implement line-breaks differently. More specifically there are `<br>` elements in the quoted bubble text, which you won't find in the real message bubbles.

![image](https://github.com/user-attachments/assets/7e653bba-b1d1-4cef-b5d7-e9278ee0e8cf)
![image](https://github.com/user-attachments/assets/518d056e-47b7-4343-93bd-e449741e8502)

This breaks the consistency of styles, since it changes spacings, especially when `line-height` is applied.

You can see how effective line height is different between the real message bubble and the quoted bubble.

![image](https://github.com/user-attachments/assets/8de799f7-2ac3-4427-a590-9267e63478e9)

The same can be observed in [the demo application](https://codesandbox.io/p/devbox/stream-chat-angular-sample-app-rc3hyw), though the difference is not as drastic given the lack of `line-height` rule.

![image](https://github.com/user-attachments/assets/9019330f-0325-49e0-9aa7-f7dfe6495e18)
![image](https://github.com/user-attachments/assets/8fac309b-49c0-499c-935e-a10323741311)

**Comment by szuperaz** [comment]
Thanks for reporting the issue, I can't provide an expected time for the fix. However, I believe that this workaround should solve the issue in the meantime:

```scss
// Solving 1.
.str-chat__message {
  .str-chat__quoted-message-bubble {
    br {
      display: none;
    }
  }
}

// Solving 2.
.str-chat__quoted-message-bubble {
  br {
    line-height: 0;
  }
}
```

![Screenshot 2024-11-04 at 17 15 06](https://github.com/user-attachments/assets/effb5389-ed18-4c19-a75a-ac36f2039648)
